### ISSUE TITLE
[PHP8] ArrayObject::asort

### ISSUE THREAD

**Issue by lewischadwick** [managur/Collection#23]
PHP8 adds the $flag param to [ArrayObject::asort](https://www.php.net/manual/en/arrayobject.asort.php)

`public ArrayObject::asort ( int $flags = SORT_REGULAR ) : void`

This causes a Fatal Error when trying to use this method.

`PHP Fatal error:  Declaration of Managur\Collection\Collection::asort(?callable $callable = null): Managur\Collection\Collection must be compatible with ArrayObject::asort(int $flags = SORT_REGULAR) in /app/vendor/managur/collection/src/Collection.php on line 393`

Need to implement the $flags param and handle the additional behaviours of the flags.

- PHP version - 8.0.1
- Managur/collection version - 1.7.2

**Comment by Antnee** [comment]
Thanks @lewischadwick. We need to implement PHP 8 support properly, including setting a 7.x constraint on v1, so I'll assign this for v2 and will investigate soon
