### ISSUE TITLE
Add `keyBy` method

### ISSUE THREAD

**Issue by ntzm** [managur/Collection#6]
I find this method useful on other collection implementations.

```php
$users = [
    [
        'name' => 'Bob',
        'age' => 42,
    ],
    [
        'name' => 'Fred',
        'age' => 31,
    ],
    // ...
];

$usersKeyedByName = (new Collection($data))
    ->keyBy(function (array $user): string {
        return $user['name'];
    })
    ->getArrayCopy();

$usersKeyedByName === [
    'Bob' => [
        'name' => 'Bob',
        'age' => 42,
    ],
    'Fred' => [
        'name' => 'Fred',
        'age' => 31,
    ],
    // ...
];
```

**Comment by Antnee** [comment]
How would you expect the example to work if you've collected this array?
```php
$users = [
    [
        'name' => 'Bob',
        'age' => 42,
    ],
    [
        'name' => 'Fred',
        'age' => 31,
    ],
    [
        'name' => 'Bob',
        'age' => 26,
    ],
    // ...
];
```
Only one of the Bobs would appear (presumably the latter).

I'm thinking about the use case. Are you more likely to use on an ID? For example, the user's ID in the DB? If so, would it make more sense to allow you to define how the collection should be keyed? So if you did this:

```php
$userCollection[] = $user;
```
... and you've configured the collection to override the key to be `$user->id()`, you would be able to retrieve the user automatically by `$userCollection[$user->id()]`, for example?

**Comment by Antnee** [comment]
I'll update this since @ntzm and I have just spoken verbally on the subject.

The problem that we're trying to solve here is indeed how to index your collectibles. My suggestion is that we instead implement a `keyStrategy()` method that might look something like this:
```php
/** @param User $collectible */
protected function keyStrategy($collectible)
{
    return $collectible->id()->asString();
}
```
We'll call this when we `append()` or `offsetSet()`, and that will mean that this:
```php
$user = new User('bobId1', 'Bob', '42');
$collection = new UserCollection($user);
```
... allows us to retrieve 42 year old Bob with:
```php
$bob = $collection['bobId1'];
```

Taking that a step further:
```php
$collection = new UserCollection([
    new User('bobId1', 'Bob', 42),
    new User('fredId1', 'Fred', 31),
    new User('bobId2', 'Bob', 26),
]);

var_dump($collection->getArrayCopy());
```
will return an array of these objects, keyed by their ID
